### ISSUE TITLE
Bug: stop timer command opens modal

### ISSUE THREAD

**Issue by ljantzen** [mcndt/obsidian-toggl-integration#10] opened 2021-08-17 11:51 UTC
When presented with the 'Select a project' prompt, all I get is `(No Project)`. ![image](https://user-images.githubusercontent.com/67438/129720485-6c5f8b4c-121c-45cf-aa82-cb9ea3bd5c7a.png).

Selecting `Donw Arrow` or `Up Arrow` does nothing. 

I am able to start timer, but it is not associated with any project.  I have a number of clients and projects in my workspace.

**Comment by mcndt** [comment] 2021-08-17 12:02
Have you selected your Toggl workspace in the plugin settings? Currently I don't support using mixed workspaces, so you have to set it at setup.

**Comment by ljantzen** [comment] 2021-08-17 12:04
Yes workspace is selected. 

But restarting Obsidian seemed to do something.  I now get the project list, and a list of existing timers. Good! 

But invoking `Stop Timer`  presents me with the `Select a project` prompt again.  If I create a new timer, the old timer is stopped, and a new timer started.  But if I just want to stop the timer (and not start a new one) the running timer is not stopped.

**Comment by mcndt** [comment] 2021-08-17 12:06
> But invoking Stop Timer presents me with the Select a project prompt again. If I create a new timer, the old timer is stopped, and a new timer started. But if I just want to stop the timer (and not start a new one) the running timer is not stopped. 

What a strange bug! I can reproduce it here. I'll see if I can fix it today or tomorrow! But to help you for now, the stop timer button in the sidebar view works as intended.

**Comment by mcndt** [comment] 2021-08-17 12:07
Also if you find a way to reproduce the empty project list, please let me know so I can look into fixing that bug as well

**Comment by ljantzen** [comment] 2021-08-17 12:21
On a side note: How do I open the Toggl sidebar view?  I cant find it...

**Comment by ljantzen** [comment] 2021-08-17 12:34
And another Obsidian restart solved that as well..

**Comment by mcndt** [comment] 2021-08-17 12:36
Glad you could get it working. I should add a command for opening it manually though. Sorry for your frustrating experience so far. Your feedback will go a long way to make the plugin better!

**Comment by ljantzen** [comment] 2021-08-17 12:39
Tank you for an excellent and useful plugin, even though it is a little rough around the edges. :-D

**Comment by mcndt** [comment] 2021-08-17 12:52
Fixed in release 0.2.2, currently live in obsidian plugin marketplace.

**Closed by mcndt** 2021-08-17 12:52 UTC
Labels: bug
