### ISSUE TITLE
How to reopen report panel after accidentally closing it?

### ISSUE THREAD

**Issue by joeyscave** [mcndt/obsidian-toggl-integration#146] opened 2023-12-28 00:10 UTC

**Comment by leoccyao** [comment] 2024-01-02 17:03
Currently: unload and reload the plugin, or run `app.plugins.plugins['obsidian-toggl-integration'].initLeaf()` in the console

**Comment by leoccyao** [comment] 2024-01-02 18:17
Also dupe of #11

**Closed** 2024-07-14 17:44 UTC

**Comment by mcndt** [comment] 2024-07-14 18:00
Will be released in 0.12.0
