### ISSUE TITLE
Project is unknown while running

### ISSUE THREAD

**Issue by danieltomasz** [mcndt/obsidian-toggl-integration#65] opened 2022-02-18 12:03 UTC
I am om latest plugin versiona and obsidian 0.13.23 (macoS 12.2)
While running I am getting Unknown project, which is later displayed correctly (Currently is running "Fens poster abstract project)
![image](https://user-images.githubusercontent.com/7980381/154679523-678239c8-41a1-48fe-8fc3-eec5025df57c.png)

**Comment by mcndt** [comment] 2022-02-20 08:55
This is a super frustrating bug that I also encounter frequently. So rest assured it's definitely on my mind 😉 

This is a duplicate of #32 so I will move this discussion there.

**Closed** 2022-02-20 08:55 UTC
Labels: duplicate
